# Generated by Django 5.2.5 on 2025-08-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-start_date', 'name'], 'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.RemoveField(
            model_name='program',
            name='id',
        ),
        migrations.RemoveField(
            model_name='program',
            name='slug',
        ),
        migrations.AddField(
            model_name='program',
            name='ProgramId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='program',
            name='focus_areas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='national_alignment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='program',
            name='phases',
            field=models.TextField(blank=True),
        ),
    ]
