# Generated by Django 5.2.5 on 2025-08-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_program_options_remove_program_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('partner', models.CharField(choices=[('UniPod', 'UniPod'), ('UIRI', 'UIRI'), ('Lwera', 'Lwera')], max_length=50)),
                ('facility_type', models.CharField(choices=[('Laboratory', 'Laboratory'), ('Workshop', 'Workshop'), ('Testing Center', 'Testing Center'), ('Maker Space', 'Maker Space')], max_length=50)),
                ('capabilities', models.CharField(choices=[('CNC', 'CNC'), ('PCB Fabrication', 'PCB Fabrication'), ('Materials Testing', 'Materials Testing')], max_length=200)),
            ],
        ),
    ]
