# Generated by Django 5.2.5 on 2025-08-31 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ProjectId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('nature_of_project', models.CharField(choices=[('Research', 'Research'), ('Prototype', 'Prototype'), ('Applied Work', 'Applied Work')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('innovation_focus', models.CharField(blank=True, max_length=200)),
                ('prototype_stage', models.CharField(choices=[('Concept', 'Concept'), ('Prototype', 'Prototype'), ('MVP', 'MVP'), ('Market Launch', 'Market Launch')], max_length=100)),
                ('testing_requirements', models.TextField(blank=True)),
                ('commercialization_plan', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.facility')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.program')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
