# Generated by Django 5.2.5 on 2025-09-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='facility',
            new_name='faciltymodels',
        ),
        migrations.AlterField(
            model_name='project',
            name='innovation_focus',
            field=models.CharField(choices=[('IoT devices', 'IoT devices'), ('Smart Home', 'Smart Home'), ('Renewable Energy', 'Renewable Energy')], max_length=200),
        ),
    ]
