# Generated by Django 5.2.5 on 2025-09-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_facility_project_faciltymodels_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='faciltymodels',
            new_name='facility',
        ),
    ]
