# Generated by Django 5.2.5 on 2025-09-02 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_faciltymodels_project_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('ServiceId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Machining', 'Machining'), ('Testing', 'Testing'), ('Training', 'Training')], max_length=50)),
                ('skill_type', models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('Integration', 'Integration')], max_length=50)),
                ('FacilityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.facility')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
