# Generated by Django 5.2.5 on 2025-09-02 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_faciltymodels_project_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('OutcomeId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('artifact_link', models.URLField(blank=True)),
                ('outcome_type', models.CharField(choices=[('CAD', 'CAD'), ('PCB', 'PCB'), ('Prototype', 'Prototype'), ('Report', 'Report'), ('Business Plan', 'Business Plan')], max_length=100)),
                ('quality_certification', models.CharField(blank=True, max_length=200)),
                ('commercialization_status', models.CharField(choices=[('Demoed', 'Demoed'), ('Market Linked', 'Market Linked'), ('Launched', 'Launched')], max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='core.project')),
            ],
            options={
                'verbose_name': 'Outcome',
                'verbose_name_plural': 'Outcomes',
            },
        ),
    ]
