# Generated by Django 5.2.5 on 2025-09-02 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('ParticipantId', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('affiliation', models.CharField(blank=True, max_length=100, null=True)),
                ('specialization', models.CharField(choices=[('CS', 'Computer Science'), ('SE', 'Software Engineering'), ('ENG', 'Engineering'), ('OTH', 'Other')], max_length=50)),
                ('cross_skill_trained', models.BooleanField(default=False)),
                ('institution', models.CharField(choices=[('SCIT', 'SCIT'), ('CEDAT', 'CEDAT'), ('UNIPOD', 'UniPod'), ('UIRI', 'UIRI'), ('LWERA', 'Lwera')], max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.project')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
            },
        ),
    ]
