# Generated by Django 4.2.23 on 2025-09-02 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('capabilities', models.CharField(blank=True, max_length=200)),
                ('inventory_code', models.CharField(blank=True, max_length=100)),
                ('usage_domain', models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Mechanical', 'Mechanical'), ('IoT', 'IoT')], max_length=50)),
                ('support_phase', models.CharField(blank=True, choices=[('Training', 'Training'), ('Prototyping', 'Prototyping'), ('Testing', 'Testing'), ('Commercialization', 'Commercialization')], max_length=50)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='core.facility')),
            ],
        ),
    ]
