# Generated by Django 5.2.5 on 2025-09-02 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_equipment'),
        ('core', '0008_participant'),
    ]

    operations = [
    ]
