# Generated by Django 5.2.5 on 2025-09-03 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('capabilities', models.TextField(blank=True, help_text='Key capabilities of this equipment')),
                ('description', models.TextField(blank=True)),
                ('inventory_code', models.CharField(help_text='Unique inventory tracking code', max_length=50, unique=True)),
                ('usage_domain', models.CharField(choices=[('Research', 'Research'), ('Development', 'Development'), ('Testing', 'Testing'), ('Production', 'Production'), ('Education', 'Education')], max_length=50)),
                ('support_phase', models.CharField(choices=[('Prototype', 'Prototype'), ('Development', 'Development'), ('Testing', 'Testing'), ('Production', 'Production'), ('Maintenance', 'Maintenance')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='core.facility')),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'ordering': ['name'],
            },
        ),
    ]
