# Generated by Django 5.2.5 on 2025-09-22 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_outcome'),
        ('core', '0009_equipment'),
    ]

    operations = [
    ]
