# Generated by Django 5.2.7 on 2025-10-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_0007_outcome_0009_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='phases',
            field=models.CharField(blank=True, choices=[('Cross-Skilling', 'Cross-Skilling'), ('Collaboration', 'Collaboration'), ('Technical Skills', 'Technical Skills'), ('Prototyping', 'Prototyping'), ('Commercialization', 'Commercialization')], max_length=50),
        ),
    ]
