# Generated by Django 5.2.5 on 2025-10-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_program_phases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='focus_areas',
            field=models.CharField(blank=True, choices=[('IoT', 'Internet of Things (IoT)'), ('Automation', 'Automation'), ('Renewable Energy', 'Renewable Energy'), ('AI', 'Artificial Intelligence'), ('Machine Learning', 'Machine Learning'), ('Robotics', 'Robotics'), ('Smart Cities', 'Smart Cities')], max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='national_alignment',
            field=models.CharField(blank=True, choices=[('NDPIII', 'NDPIII - National Development Plan III'), ('DigitalRoadmap2023_2028', 'Digital Roadmap 2023-2028'), ('4IR', '4IR - Fourth Industrial Revolution')], max_length=50),
        ),
    ]
